### ISSUE TITLE
[BUG] Large Inflation in bounding box co-ordinate values when exporting datasets through different formats

### ISSUE THREAD

**Issue by neel04** [voxel51/fiftyone#1381] opened 2021-10-29 00:17 UTC
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Kaggle`
-   **FiftyOne installed from (pip or source)**: `pip`
-   **FiftyOne version (run `fiftyone --version`)**: `FiftyOne v0.14.0`
-   **Python version**: `3.7.10`

### Commands to reproduce

Given a Pandas `Dataframe`, I am attempting to convert it to a FiftyOne dataset which is successful (✔️ )

```py
for row in tqdm(train_df.iloc()):
    bboxes, class_labels, detections = [], [], []
    ID, image_class, xmin, ymin, width, height = row.to_numpy()
    
    image = cv2.imread(f'/kaggle/input/zindi-makere-plant-disease-classification/Train_Images/Train_Images/{ID}.jpg',cv2.IMREAD_COLOR)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    for classes, xmins, ymins, widths, heights in zip(image_class, xmin, ymin, width, height):
        bboxes.append([xmins, ymins, widths, heights])
        class_labels.append(classes)

    transformed_image = image
    transformed_bboxes = bboxes
    transformed_class_labels = class_labels
    
    cv2.imwrite(f'./temp/{ID}_OG.jpg', transformed_image)
    sample = fo.Sample(filepath=f'./temp/{ID}_OG.jpg')
    
    for classes, t_bbox in zip(transformed_class_labels, transformed_bboxes):
        detections.append(fo.Detection(label=classes, bounding_box=list(t_bbox), iscrowd=0))
        
    
    # Store detections in a field name of your choice
    sample["bounding_box"] = fo.Detections(detections=detections)
    sample["iscrowd"] = 0
    samples.append(sample)

random.shuffle(samples)
aug_train_dataset = fo.Dataset("aug_train_datset") #'training_dataset'
aug_train_dataset.add_samples(samples)
```

For reproducing the above, setting hard-coded example values would suffice to recreate the same dataset I am using 👍 
Also, manual iteration suggests that the samples are correctly formatted, more information below:-

### Describe the problem

The problem is very simple, this is how iterating over the `FiftyOne` dataset looks like:-

```py
<Sample: {
    'id': '6168b1d427a1b2f1d4a4cf95',
    'media_type': 'image',
    'filepath': '/kaggle/working/temp/ID_CYJZQHZS_OG.jpg',
    'tags': BaseList([]),
    'metadata': None,
    'bounding_box': <Detections: {
        'detections': BaseList([
            <Detection: {
                'id': '6168b1ce27a1b2f1d4a4cd8e',
                'attributes': BaseDict({}),
                'tags': BaseList([]),
                'label': 'fruit_brownspot',
                'bounding_box': BaseList([239.5, 32.5, 260.0, 330.0]),
                'mask': None,
                'confidence': None,
                'index': None,
                'iscrowd': 0,
            }>,
        ]),
    }>,
    'iscrowd': 0,
}>
```

from what I gather, this sample looks perfectly fine for the FiftyOne format. trouble happens when I try to export it to a `COCO` dataset, and then read the JSON created from the `COCO` dataset holding the annotations, the `bounding_box` field clearly indicates the problem:-

```py
[{'id': 1,
  'image_id': 1,
  'category_id': 2,
  'bbox': [136051.88284518826,
   94522.21453722335,
   223827.3012552301,
   196733.29351106644],
  'area': 44034282153.63507,
  'iscrowd': 0},
 {'id': 2,
  'image_id': 2,
  'category_id': 2,
  'bbox': [0.0, 88064.0, 77824.0, 76544.0],
  'area': 5956960256.0,
  'iscrowd': 0},
  .........................
```
so it seems that the BBOX co-ords are just blown up when exporting 🤔 (**NOTE** both samples given above are not necessarily the same)

Code for exporting:-

```py
dataset_or_view = aug_train_dataset
export_dir = "augmented_train_coco"
dataset_type = fo.types.COCODetectionDataset
dataset_or_view.export(
    export_dir=export_dir,
    dataset_type=dataset_type,
    label_field='bounding_box',
    classes=class_list
)
```

- [x] `TASK ==>` Object Detection + classification of detected objects

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment] 2021-11-03 15:14
You'll just need to rescale to `[0, 1]` in whatever code you're using to create your dataset. It must be Python code of your own writing, because when you use a builtin importer like [COCODetectionDataset](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cocodetectiondataset), any necessary rescaling will automatically be done for you.

If you want to access absolute pixel coordinates for your detections, you can use `dataset.compute_metadata()` to populate the `metadata` field of your samples and then do the necessary conversions in code like so:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

# Popuulate `metadata` field of all samples
dataset.compute_metadata()

# Grab a sample
sample = dataset.first()

# Grab a detection
detection = sample.ground_truth.detections[0]

# Convert bbox to pixel coordinates
width = sample.metadata.width
height = sample.metadata.height
x, y, w, h = detection.bounding_box
bbox = [x * width, y * height, w * width, h * height]
print(bbox)  # [134.94, 1.65, 295.62, 453.22]
```

We like standardizing on relative coordinates in our data model because it enables for things like swapping out different resolution versions of images. It could be interesting, though, to add a property to classes like `Detection` that will automatically do the conversion from relative to absolute coordinates.

**Comment by brimoor** [comment] 2021-11-03 15:15
Closing this because it is not a bug; a feature request for absolute coordinates is welcome if desired though.

**Closed by brimoor** 2021-11-03 15:15 UTC
Labels: bug
