### ISSUE TITLE
[BUG] Partially initialized module 'fiftyone.core.odm.database' has no attribute 'set_default_port' (most likely due to a circular import)

### ISSUE THREAD

**Issue by jaffe-fly** [voxel51/fiftyone#1107] opened 2021-07-08 10:37 UTC
### Instructions

when i run ```from flash.image import ImageClassificationData, ImageClassifier```

error occurs
```
AttributeError: partially initialized module 'fiftyone.core.odm.database' has no attribute 'set_default_port' (most likely due to a circular import)

```

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: linux
-   **FiftyOne installed from (pip or source)**:pip
-   **FiftyOne version (run `fiftyone --version`)**: fiftyone     0.11.1/fiftyone-brain     0.6.1/fiftyone-db           0.2.1
-   **Python version**:3.8

**Comment by benjaminpkane** [comment] 2021-07-08 16:23
Hi @jaffe-fly. Can you provide any more information? A full stack trace would be helpful. I'm unable to reproduce.

**Comment by brimoor** [comment] 2021-07-08 21:20
I'm unable to reproduce either. From a fresh virtual environment, I ran:

```
pip install lightning-flash 'lightning-flash[image]'
```

and then

```py
from flash.image import ImageClassificationData, ImageClassifier
```

with no issues.

**Comment by jaffe-fly** [comment] 2021-07-09 01:38
i am pip install the package in my jupyterlab ，lab info is：
```
#cat /proc/version 
Linux version 3.10.0-1127.13.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Jun 23 15:46:38 UTC 2020
# cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
```
i use this command to install ```pip install git+https://github.com/PytorchLightning/lightning-flash.git@master#egg=lightning-flash[image]```

![image](https://user-images.githubusercontent.com/49515380/125010568-5e33c000-e099-11eb-9a3d-de883b6cfb7a.png)

**Comment by brimoor** [comment] 2021-07-09 01:51
Hmm, I didn't try in JupyterLab, but this was successful for me on the same OS:

```shell
cat /etc/issue
# Ubuntu 18.04.5 LTS \n \l

conda create -n tmp python=3.8
conda activate tmp

pip install git+https://github.com/PytorchLightning/lightning-flash.git@master#egg=lightning-flash[image]
pip install ipython
```

```py
from flash.image import ImageClassificationData, ImageClassifier  # works
```

**Comment by jaffe-fly** [comment] 2021-07-09 02:19
en  i dont know why ，i am really encountered

**Comment by brimoor** [comment] 2021-07-10 15:26
I'm still not sure how to make any progress on this, but my best guess is that something went wrong with your `pip install fiftyone`. If you try directly installing FiftyOne and then doing `import fiftyone as fo`, then we might learn more about what might be going wrong with your install.

If you're just looking to use Flash but don't want to use FiftyOne (we won't hold it against you, but you should check it out sometime 😉 ), then here's a couple suggestions:
- https://github.com/PyTorchLightning/lightning-flash/pull/491 updated Flash to only import FiftyOne if it is actually being used. I'm not sure if it has been included in a Flash release yet, but you could do a source install on their `master` branch and then you'd have it. With that change, a broken FiftyOne install won't affect your ability to use the Flash library
- FiftyOne was added in `flash==0.4.0`, so if you install an older version of Flash, that should unblock you until https://github.com/PyTorchLightning/lightning-flash/pull/491 is included in a release

**Comment by swheaton** [comment] 2023-10-07 12:30
No further response, closing.

**Closed by swheaton** 2023-10-07 12:30 UTC
Labels: bug
