### ISSUE TITLE
[FR] Maintain scroll position when tagging in the App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#1500] opened 2022-01-02 18:24 UTC
When using the App's [tagging UI](https://voxel51.com/docs/fiftyone/user_guide/app.html#tags-and-tagging), applying a tag change currently:
- Reloads the view
- Resets the scroll position to the first page
- Retains any currently selected samples

In many cases, a user may be working through a view and applying tags incrementally, in which case resetting the scroll position is inconvenient as one must then scroll back to where you left off, which may be difficult to remember and/or far away from the first page. Of course, editing tags may change the contents of the current view, eg if the view contains a `match_tags()` stage, so maintaining the "current scroll position" requires a bit of care. One heuristic could be to load the page whose first sample matches the first sample in the old page. Or more generally (in case the first sample is no longer in the view) select the page that maximizes the overlap with the samples in the old page.

I would also argue that, more often than not, after applying a tag change, the user is "done" with the samples/labels in question and therefore it would be better to always clear the current selection after tagging.

<img width="1269" alt="Screen Shot 2022-01-02 at 1 13 51 PM" src="https://user-images.githubusercontent.com/25985824/147885569-df2a8b27-adf0-4e8d-8b96-62e4df84eaee.png">

**Comment by benjaminpkane** [comment] 2022-01-03 14:32
This has been discussed offline. Behavior like this would come starts with a scrubbable grid, i.e. where the grid could start at an arbitrary index (or sample id) and tile in either direction (up or down).

**Comment by benjaminpkane** [comment] 2022-01-03 14:39
Duplicate of #1072

**Closed by benjaminpkane** 2022-01-03 14:39 UTC
Labels: enhancement, app
