### ISSUE TITLE
Spurious error when connecting to remote session?

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#468] opened 2020-08-27 19:45 UTC
I connected to a remote session as follows:

```py
import fiftyoneas fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

# Remote
session = fo.launch_app(dataset=dataset, remote=True)
```

```
# Local
fiftyone app connect --destination [<username>@]<hostname> --port 5151
```

On the local machine, I see:

```
Connected to fiftyone on local port 5151
If you are not connecting to a remote session, you may need
to start a new session and specify a port.

App launched

To exit, close the app or press ctrl + c
```

Then, on the remote machine, I do:

```py
session.view = dataset.take(10)
```

On the local machine, the App updates as expected. Things seem to be working as expected. However, in the shell running the App, I see this (non-fatal) error:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 260, in get
    result = next(queryset)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 1590, in __next__
    raw_doc = next(self._cursor)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/pymongo/cursor.py", line 1164, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 1465, in _load_dataset
    dataset_doc = foo.DatasetDocument.objects.get(name=name)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 263, in get
    raise queryset._document.DoesNotExist(msg)
fiftyone.core.odm.dataset.DoesNotExist: DatasetDocument matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/socketio/client.py", line 613, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/socketio/client.py", line 497, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/socketio/client.py", line 552, in _trigger_event
    event, *args)
  File "/Users/Brian/dev/env/fifty3/lib/python3.6/site-packages/socketio/namespace.py", line 18, in trigger_event
    return getattr(self, handler_name)(*args)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/client.py", line 64, in on_update
    self.data = self.data_cls.from_dict(data)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/state.py", line 80, in from_dict
    dataset = fod.load_dataset(dataset.get("name"))
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 83, in load_dataset
    return Dataset(name, _create=False)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/singleton.py", line 36, in __call__
    instance.__init__(name=name, _create=_create, *args, **kwargs)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 174, in __init__
    self._doc, self._sample_doc_cls = _load_dataset(name)
  File "/Users/Brian/dev/fiftyone/fiftyone/core/dataset.py", line 1467, in _load_dataset
    raise DoesNotExistError("Dataset '%s' not found" % name)
fiftyone.core.dataset.DoesNotExistError: Dataset 'quickstart' not found
```

**Comment by lethosor** [comment] 2020-08-27 19:51
Duplicate of #208

**Closed by lethosor** 2020-08-27 19:51 UTC
Labels: app, bug, core
