### ISSUE TITLE
[BUG] Can't view video datasets with `metadata` in App

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#626] opened 2020-10-22 20:51 UTC
When trying to load a video dataset with `fiftyone.core.labels.VideoMetadata` values in its `metadata` field, I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 108, in wrapper
    return func(self, *args, **kwargs)
  File "main.py", line 316, in on_get_frame_labels
    field_labels = _make_image_labels(k, v, frame_number)
  File "main.py", line 156, in _make_image_labels
    fol.ImageLabel.from_dict(label).to_image_labels(name=name),
AttributeError: 'VideoMetadata' object has no attribute 'to_image_labels'
```

After setting the `metadata` to `None`, I can then visualize the dataset.

**Comment by brimoor** [comment] 2020-10-22 21:11
Update: this happens when working with the attached dataset from a remote session, but not from a local session...

[pip-175k-sample.zip](https://github.com/voxel51/fiftyone/files/5425828/pip-175k-sample.zip)

Here's what I did:

```py
import fiftyone as fo

dataset = fo.Dataset.from_dir(
    "/path/to/pip-175k-sample",
    fo.types.FiftyOneDataset
)

dataset.compute_metadata()

session = fo.launch_app(dataset)
```

**Comment by lethosor** [comment] 2020-10-22 21:13
> Update: this happens when working with the attached dataset from a remote session, but not from a local session...

This is a likely duplicate of #208, in that case.

**Comment by brimoor** [comment] 2020-10-22 21:24
Update to the update: this just happened in a local session too

**Closed** 2020-11-09 16:21 UTC
Labels: app, bug
