### ISSUE TITLE
[BUG] Storing Classifications in Detections causes a ValidationError

### ISSUE THREAD

**Issue by geoffrp** [voxel51/fiftyone#2002] opened 2022-08-16 18:50 UTC
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.5
-   **Python version**: 3.9.10

### Commands to reproduce

Below is a python script that:

1. Creates a dataset
2. Adds a detection
3. Adds a classification as a field under the detection
4. Should cause a ValidationError when trying to load back the `Sample`

```
from pathlib import Path

import fiftyone as fo

# Make a 1 image dataset and make it persistent
dataset = fo.Dataset.from_images_dir(Path(__file__).parent.joinpath("images"))
dataset.name = "bug_or_im_wrong"
dataset.persistent = True
dataset.compute_metadata()

# Open it up and add some a detection
sample = dataset.first()
sample["dog_boxes"] = fo.Detections(
    detections=[fo.Detection(label="dog", bounding_box=[0.1, 0.1, 0.1, 0.1])]
)
sample.save()
# Remove the sample (close the connection...?),
del sample

# Open the sample again to add classifications to the detection
sample = dataset.first()

detection = sample["dog_boxes"].detections[0]
detection["dog_type"] = fo.Classifications(
    classifications=[
        fo.Classification(label="happy"),
        fo.Classification(label="golden"),
    ]
)
# Save and remove it from scope
sample.save()
del sample

# Reopen and it should raise a validation error
sample = dataset.first()
```

### Describe the problem

For two stage classification workflows, storing classification(s) under a detection is necessary for orchestrating multiple models to act as one system.  Attributes from CVAT annotations should be able to be compared to classifications on predicted samples to interpret overall system performance.

### Code to reproduce issue

See above

### Other info / logs

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached. Please do not use screenshots for sharing text. Code
snippets should be used instead when providing tracebacks, logs, etc.

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment] 2022-08-16 20:13
I believe this is a duplicate of https://github.com/voxel51/fiftyone/issues/1769 and will be fixed (ie nested `Label` types will be supported) in the next release.

https://github.com/voxel51/fiftyone/pull/1922 resolves this.

**Closed by brimoor** 2022-08-16 20:13 UTC
Labels: bug
