### ISSUE TITLE
[BUG] import_annotations from cvat, not show annotation

### ISSUE THREAD

**Issue by muhammadAgfian96** [voxel51/fiftyone#2325] opened 2022-11-18 07:59 UTC
### Instructions

Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md) for information on what types of issues we address.

1. Please fill in this template to ensure a timely and thorough response
2. Place an "x" between the brackets next to an option if it applies. For example:
    -   [x] Selected option
3. **Please delete everything above this line before submitting the issue**

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): PopOS 22.04
-   **Python version** (`python --version`): Python 3.7.7
-   **FiftyOne version** (`fiftyone --version`): 0.18, 0.17.2
-   **FiftyOne installed from** (pip or source): pip
- **Cvat Version**:
-- Server version: 1.7
-- Core version: 3.17.0
-- Canvas version: 2.8.0
-- UI version: 1.25.0

### Commands to reproduce

`test.py`
```
import fiftyone as fo
import fiftyone.utils.cvat as fouc

dataset = fo.Dataset()
fouc.import_annotations(
    dataset,
    task_ids=[192],
    data_path="tmp/cvat_import",
    download_media=True,
    backend='cvat'
)
dataset.compute_metadata()
session_one = fo.launch_app(dataset, port=4441)
session_one.wait()
```

```
python test.py
```

### Describe the problem

cannot show annotation on fiftyone, only show image downloaded from cvat .

### Code to reproduce issue

-

### Other info/logs

no error/warning reported

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment] 2022-11-18 14:43
Can you share the outputs of these?

```
print(dataset)
print(dataset.first())
```

**Comment by muhammadAgfian96** [comment] 2022-11-18 16:07
```
dataset:
Name:        2022.11.18.23.05.19
Media type:  image
Num samples: 50
Persistent:  False
Tags:        []
Sample fields:
    id:       fiftyone.core.fields.ObjectIdField
    filepath: fiftyone.core.fields.StringField
    tags:     fiftyone.core.fields.ListField(fiftyone.core.fields.StringField)
    metadata: fiftyone.core.fields.EmbeddedDocumentField(fiftyone.core.metadata.ImageMetadata)

dataset_first:
<Sample: {
    'id': '6377ad4555c1e2513b659257',
    'media_type': 'image',
    'filepath': '/home/agfian/x/x/x/x/day1_set3_side1_20220715123234_a54766e107794a26a6f55b3c79889320.jpg',
    'tags': [],
    'metadata': <ImageMetadata: {
        'size_bytes': 74334,
        'mime_type': 'image/jpeg',
        'width': 320,
        'height': 364,
        'num_channels': 3,
    }>,
}>
```

**Comment by brimoor** [comment] 2022-11-18 16:25
Yeah so the problem is that `fouc.import_annotations()` didn't find any labels to import. If it did, you would have fields called `classification`, `detections`, etc depending on the type of labels in the task.

Are you seeing any errors? Are you sure that the CVAT task has annotations saved in it?

**Comment by muhammadAgfian96** [comment] 2022-11-18 16:31
yeah, it's kind of weird, last time I run, the annotations were shown, but right now there is no annotation.
I also checked annotations on the CVAT task, it has annotations.

is there a way to attach annotations manually? maybe I can download and attach manually annotations.

**Comment by brimoor** [comment] 2022-11-18 16:35
You could always download the annotations from CVAT to disk and then import them using `Dataset.from_dir()`. For example FiftyOne supports [CVATImageDataset format](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cvatimagedataset).

**Comment by muhammadAgfian96** [comment] 2022-11-18 17:15
Thanks @brimoor , it works! the image and annotations shown. but sadly, compute_metadata() only generate width and height.

```import fiftyone as fo
import fiftyone.zoo as foz

name = "my-dataset1"
dataset_dir = "/home/agfian/x/x/tmp/cvat_194"

# Create the dataset
dataset = fo.Dataset.from_dir(
    dataset_dir=dataset_dir,
    labels_path='/home/agfian/x/x/tmp/cvat_194/annotations.xml',
    dataset_type=fo.types.CVATImageDataset,
)

# View summary info about the dataset

# Print the first few samples in the dataset
dataset.compute_metadata()
session_one = fo.launch_app(dataset, port=4441)
session_one.refresh()
session_one.wait()`
```

folder strcuture dataset_dir:
```
/home/agfian/x/x/tmp/cvat_194
├── annotations.xml
└── data
    └── x
        └── x
            └── x
                ├── 0e5cf9421d4c48f8b8b0ba00d0cba931.jpg
                ├── 102b0c0158f340ba9aded871d3bb2e37.jpg
                ├── 1978ce747a6c4799bf5d28f8ce109958.jpg
                ├── 1ba4987a55fa446daa00312832f62d13.jpg
                ├── 21ffb4f92f484700883812c851bd123a.jpg
```

should we close the issue, since we have another way to do that?

**Comment by brimoor** [comment] 2022-11-18 17:20
When you import annotations from certain formats like CVAT, some metadata might be available from the annotations and are thus populated automatically when you import.

You can pass `overwrite=True` if you want to regenerate metadata with all fields populated:

```
dataset.compute_metadata(overwrite=True)
```

**Comment by brimoor** [comment] 2022-11-18 17:21
We never solved your actual issue, but this comment:
> last time I run, the annotations were shown, but right now there is no annotation

seems to imply there is no bug in FiftyOne, so, yes let's close the issue.

**Closed by brimoor** 2022-11-18 17:21 UTC
Labels: bug

**Comment by muhammadAgfian96** [comment] 2022-11-21 06:20
Hi @brimoor , 
i tried this on [cvat.app.](https://app.cvat.ai/) and fiftyone 0.18 on different machine, still the annotations is not shown. also the 0.18 there is bug when doing this.

> Thanks @brimoor , it works! the image and annotations shown. but sadly, compute_metadata() only generate width and height.
> 
> ```
> import fiftyone.zoo as foz
> 
> name = "my-dataset1"
> dataset_dir = "/home/agfian/x/x/tmp/cvat_194"
> 
> # Create the dataset
> dataset = fo.Dataset.from_dir(
>     dataset_dir=dataset_dir,
>     labels_path='/home/agfian/x/x/tmp/cvat_194/annotations.xml',
>     dataset_type=fo.types.CVATImageDataset,
> )
> 
> # View summary info about the dataset
> 
> # Print the first few samples in the dataset
> dataset.compute_metadata()
> session_one = fo.launch_app(dataset, port=4441)
> session_one.refresh()
> session_one.wait()`
> ```
> 
> folder strcuture dataset_dir:
> 
> ```
> /home/agfian/x/x/tmp/cvat_194
> ├── annotations.xml
> └── data
>     └── x
>         └── x
>             └── x
>                 ├── 0e5cf9421d4c48f8b8b0ba00d0cba931.jpg
>                 ├── 102b0c0158f340ba9aded871d3bb2e37.jpg
>                 ├── 1978ce747a6c4799bf5d28f8ce109958.jpg
>                 ├── 1ba4987a55fa446daa00312832f62d13.jpg
>                 ├── 21ffb4f92f484700883812c851bd123a.jpg
> ```
> 
> should we close the issue, since we have another way to do that?

so i downgrade to 0.17.2 and it works for manual, but still import_annotations, not shown.
