### ISSUE TITLE
[BUG] Error: DOM element provided is null or undefined

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#2709] opened 2023-03-02 13:50 UTC
With patches in the grid and patch embeddings in the panel, clearing the view bar results in the following error:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
model = foz.load_zoo_model("clip-vit-base32-torch")

embeddings = dataset.compute_patch_embeddings(model, "ground_truth")
fob.compute_visualization(
    dataset,
    embeddings=embeddings,
    patches_field="ground_truth",
    brain_key="gt_viz",
)

session = fo.launch_app(dataset)
```

```
Error: DOM element provided is null or undefined
at Object.r [as getGraphDiv] (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.a5fcf1b2.js:5737:1224)
at Object.Et [as purge] (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.a5fcf1b2.js:5737:115837)
at C.value (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.a5fcf1b2.js:4523:5565)
at QAe (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:30550)
at Wu (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:27781)
at QAe (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:29241)
at Wu (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:27781)
at QAe (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:28093)
at Wu (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:27781)
at QAe (http://localhost:5151/datasets/quickstart-demo-0.19/assets/index.d880d008.js:63:27896)
```

<img width="1947" alt="Screen Shot 2023-03-02 at 8 47 55 AM" src="https://user-images.githubusercontent.com/25985824/222446735-1cb6c435-0fc0-4fec-8098-dc661a1d8f3e.png">

**Comment by sashankaryal** [comment] 2023-03-13 18:52
Thanks for taking a look, @imanjra!
There's yet another avenue to this error that @brimoor showed me. Load the embeddings first, and the patches view, and then clear the view bar - or I might be getting the order wrong. I did try various permutations of it and couldn't reproduce it on my end, but let's confirm with @brimoor before we shut the door on this ticket.

**Comment by brimoor** [comment] 2023-03-13 22:28
@imanjra @sashankaryal I can still reproduce this. From the state pictured above, when I clear the view bar I get this:

```
Error: DOM element provided is null or undefined
    at Object.r [as getGraphDiv] (http://localhost:5151/datasets/zzz-dom-element/assets/index.66b826f7.js:5816:1224)
    at Object.Et [as purge] (http://localhost:5151/datasets/zzz-dom-element/assets/index.66b826f7.js:5816:115837)
    at C.value (http://localhost:5151/datasets/zzz-dom-element/assets/index.66b826f7.js:4602:5565)
    at o1e (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:30550)
    at tu (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:27781)
    at o1e (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:29241)
    at tu (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:27781)
    at o1e (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:28093)
    at tu (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:27781)
    at o1e (http://localhost:5151/datasets/zzz-dom-element/assets/index.9e69629f.js:63:27896)
```

<img width="2049" alt="Screen Shot 2023-03-13 at 6 27 28 PM" src="https://user-images.githubusercontent.com/25985824/224846711-3ee8be0b-0356-4f62-9def-a4831c7efa75.png">

**Comment by imanjra** [comment] 2023-04-19 10:29
Should be fixed by https://github.com/voxel51/fiftyone/pull/2783. Please feel free to re-open it if you see it again.

**Closed by imanjra** 2023-04-19 10:29 UTC
Labels: bug, app
