### ISSUE TITLE
[BUG] [Urgent] Cifar-10/100 sample dataset can not be loaded in 0.14.2

### ISSUE THREAD

**Issue by imyhxy** [voxel51/fiftyone#1480] opened 2021-12-20 03:01 UTC
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.14.2
-   **Python version**: 3.8.3

### Commands to reproduce
```
# pip install fiftyone==0.14.2
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("cifar10", split="test")
print(dataset)
```

### Describe the problem

Exception raised:

```python
/ipykernel_864/2572829385.py in <module>
      2 import fiftyone.zoo as foz
      3 
----> 4 dataset = foz.load_zoo_dataset("cifar10", split="train", drop_existing_dataset=True, overwrite=True, cleanup=True)
      5 print(dataset)

~/miniconda3/envs/edge/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py in load_zoo_dataset(name, split, splits, label_field, dataset_name, dataset_dir, download_if_necessary, drop_existing_dataset, overwrite, cleanup, **kwargs)
    195         )
    196 
--> 197         info, dataset_dir = download_zoo_dataset(
    198             name,
    199             splits=splits,

~/miniconda3/envs/edge/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py in download_zoo_dataset(name, split, splits, dataset_dir, overwrite, cleanup, **kwargs)
    114         name, dataset_dir, **kwargs
    115     )
--> 116     return zoo_dataset.download_and_prepare(
    117         dataset_dir=dataset_dir,
    118         split=split,

~/miniconda3/envs/edge/lib/python3.8/site-packages/fiftyone/zoo/datasets/__init__.py in download_and_prepare(self, dataset_dir, split, splits, overwrite, cleanup)
   1002                     num_samples,
   1003                     classes,
-> 1004                 ) = self._download_and_prepare(split_dir, scratch_dir, split)
   1005 
   1006                 # Add split to ZooDatasetInfo

~/miniconda3/envs/edge/lib/python3.8/site-packages/fiftyone/zoo/datasets/torch.py in _download_and_prepare(self, dataset_dir, scratch_dir, split)
    191         get_class_labels_fcn = _parse_classification_labels
    192         sample_parser = foud.ImageClassificationSampleParser()
--> 193         return _download_and_prepare(
    194             dataset_dir,
    195             scratch_dir,

~/miniconda3/envs/edge/lib/python3.8/site-packages/fiftyone/zoo/datasets/torch.py in _download_and_prepare(dataset_dir, scratch_dir, download_fcn, get_class_labels_fcn, sample_parser)
    534         )
    535     else:
--> 536         raise ValueError("Unsupported label class %s" % label_cls)
    537 
    538     # Write the formatted dataset to `dataset_dir`

TypeError: not all arguments converted during string formatting
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by imyhxy** [comment] 2021-12-20 03:16
Also broken in `v0.14.1`, but work in `v0.14.0`.

**Comment by brimoor** [comment] 2021-12-20 03:30
Duplicate of https://github.com/voxel51/fiftyone/issues/1451. This is fixed by https://github.com/voxel51/fiftyone/pull/1452 on `develop` and will be included in the next release.

**Closed by brimoor** 2021-12-20 03:30 UTC
Labels: bug
