### ISSUE TITLE
[BUG] Cannot use app after creating new field for samples in my dataset

### ISSUE THREAD

**Issue by chetanmr** [voxel51/fiftyone#1867] opened 2022-06-10 20:06 UTC
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.2
-   **Python version**: 3.9.0

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```py
import fiftyone as fo

name = "val_data"
dataset_dir = " "
splits = ["val"]
val_data = fo.Dataset(name)

for split in splits:
        val_data.add_dir(
        dataset_dir=dataset_dir,
        dataset_type=fo.types.YOLOv5Dataset,
        split=split,
        tags=split,
)

val_data_copy = val_data.clone()

session = fo.launch_app(val_data_copy, port=5151)

val_data_copy.compute_metrics()

for sample in val_data_copy:
        sample["asp"] = round((sample["metadata"].width) / (sample["metadata"].height), 2)
        sample.save()
```

### Describe the problem
After adding this new field to all my samples, the app errors out with the following error when i refresh the browser tab
<img width="2477" alt="Screen Shot 2022-06-10 at 1 02 16 PM" src="https://user-images.githubusercontent.com/31442079/173142423-afce9092-842b-49ed-9d59-1053c88f8603.png">

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [X] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment] 2022-06-10 20:24
Duplicate of https://github.com/voxel51/fiftyone/issues/1853.

**Closed** 2022-06-20 20:07 UTC
Labels: bug, app
