### ISSUE TITLE
[FR] Add support for videos represented as a series of images

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#1961] opened 2022-07-21 13:33 UTC
Currently the App requires a video file defined on each video sample's `filepath`. It would be useful for to those who store videos as a series of images to support defining an image on each `FrameSample` of the video sample. The most important component of this feature will be adding support in the video visualizer (Looker).

One current workaround to work with image datasets and sort by frame number and id to navigate through images in the expanded view.

There may also be a use case for group views  in the App of image datasets that are frames of videos. See #1954

**Comment by brimoor** [comment] 2022-07-21 13:45
Closing as duplicate of https://github.com/voxel51/fiftyone/issues/1962 which provides more information and workarounds.

**Closed by brimoor** 2022-07-21 13:45 UTC
Labels: feature, app, core, needs design
