### ISSUE TITLE
[FR] Allow Sample object to reference a remote image web URL

### ISSUE THREAD

**Issue by tszumowski** [voxel51/fiftyone#1387] opened 2021-11-01 13:11 UTC
### Proposal Summary

Is it possible to create a Sample object that references a web-hosted URL of an image?

### Motivation

-   What is the use case for this feature?

I often point to catalogs of images that dynamically change over time. Using FiftyOne with this dataset requires me to periodically download all the images from a very large image catalog to a file server which can be cumbersome to manage and maintain synchronization.

-   Why is this use case valuable to support for FiftyOne users in general?

It allows users to add remote URLs, e.g. `https://remote/path/to/image.jpg` to their catalog so that everything doesn't have to be in a file server

-   Why is this use case valuable to support for your project(s) or
    organization?

For e-commerce applications, we don't have to maintain an image file-server that is synced with a hosted image server.

-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)

Without it, I need to periodically pull all images down to a file system and maintain sharing across the team.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [X] Core: Core `fiftyone` Python library
-   [X] Server: FiftyOne server

### Details

I ran a test to see if this already works.

```python
import fiftyone as fo

# Create an empty dataset
dataset = fo.Dataset("test-dataset")

# An image sample, pointed to remote URL
sample = fo.Sample(filepath="https://www.instagram.com/static/images/web/mobile_nav_type_logo.png/735145cfe0a4.png")
print(sample)

# Add sample
dataset.add_sample(sample)

# Save dataset
dataset.save()

# Start viewer
session = fo.launch_app(dataset, auto=False)
session.open_tab()
```

Upon opening, I see:
![image](https://user-images.githubusercontent.com/10282962/139676930-ecdcbbbe-3e27-4368-bf38-1b633371ef64.png)

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [X] No. I cannot contribute this feature at this time.

**Comment by benjaminpkane** [comment] 2021-11-02 13:10
Hi @tszumowski :wave: 

This feature is planned for [FiftyOne Teams](https://voxel51.com/#teams-form) and is being worked on. Closing as this a duplicate of #768

**Closed by benjaminpkane** 2021-11-02 13:10 UTC
Labels: enhancement
