### ISSUE TITLE
[BUG] TypeError exception when invoking find_duplicates

### ISSUE THREAD

**Issue by FGeri** [voxel51/fiftyone#1476] opened 2021-12-14 14:21 UTC
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.2 LTS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: v0.14.2
-   **Python version**: 3.8
-   **FiftyOne brain version: 0.7.2

### Describe the problem

I get a TypeError exception when trying to find duplicates in a dataset with around 30000 samples.
 
### Code to reproduce issue

```
fob.compute_similarity(dataset,  brain_key="similarity_imagenet")
similarity_results = dataset.load_brain_results("similarity_imagenet")
similarity_results .find_duplicates()
```

### Other info / logs

Computing embeddings...
 100% |█████████████| 30447/30447 [7.6m elapsed, 0s remaining, 40.1 samples/s]      
Generating neighbors graph for 30447 embeddings; this may take awhile...
Index complete
Computing duplicate samples...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_3212481/303551069.py in <module>
      4                         brain_key="similarity_imagenet")
      5 similarity_results_on_merged = merged_dataset.load_brain_results("similarity_imagenet")
----> 6 similarity_results_on_merged.find_duplicates()
      7 new_unique_subdataset = merged_dataset.select(similarity_results_on_merged.unique_ids)
      8 unique_filepaths_in_merged = set(new_unique_subdataset.values("filepath"))

~/venvs/datalake/lib/python3.8/site-packages/fiftyone/brain/similarity.py in find_duplicates(***failed resolving arguments***)

~/venvs/datalake/lib/python3.8/site-packages/fiftyone/brain/internal/core/similarity.py in find_duplicates(***failed resolving arguments***)

TypeError: unhashable type: 'numpy.ndarray'

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by FGeri** [comment] 2021-12-14 16:00
Hi @brimoor ,

Unfortunately no. I get the same error even after giving it a threshold.

**Comment by brimoor** [comment] 2021-12-14 16:56
Hmm okay, does the example code I shared work? And can you try running [this example too](https://voxel51.com/docs/fiftyone/user_guide/brain.html#cifar-10-example)? I'm not able to reproduce the issue yet.

**Comment by FGeri** [comment] 2021-12-14 19:00
Well, somehow foz.load_zoo_dataset("cifar10", split="test") raises `TypeError: not all arguments converted during string formatting`, so I cannot. But in general find_duplicates works, it raises the above mentioned exception only for one dataset, so probably I have some corrupted image inside or something. Nevertheless some telling error message would be nice.

**Comment by brimoor** [comment] 2021-12-14 19:05
The CIFAR-10 issue you encountered is [due to this](https://github.com/voxel51/fiftyone/issues/1451).

I've done a bit more digging and there could be an actual bug in `find_duplicates()` we need to fix. The behavior is different when there are more than 15,000 samples, which is true for your dataset but not for the smaller examples I suggested. Looking into it

**Comment by brimoor** [comment] 2021-12-14 19:32
Okay yes there was a bug in `fiftyone-brain<=0.7.2` that causes `find_duplicates()` to raise the error shown here when there are >15,000 embeddings being computed.

This bug will be fixed in the next release (coming later this week). Until then, the only workaround is to restrict to <= 15,000 samples before calling `find_duplicates()`. For example:

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

results = fob.compute_similarity(dataset, brain_key="img_sim")

# Restrict to first 100 samples (any view can be used here)
results.use_view(dataset.limit(100))

results.find_duplicates(fraction=0.01)
print(results.duplicate_ids)
```

**Comment by FGeri** [comment] 2021-12-15 06:40
Alright, thanks for the quick investigation.

**Closed** 2021-12-20 03:31 UTC
Labels: bug

**Comment by liorgreenbergmh** [comment] 2022-01-09 14:23
Hey @brimoor,
I am also experiencing the issue and that the latest version is still 0.7.2.

Was the fix you mentioned actually released?

**Comment by brimoor** [comment] 2022-01-09 14:45
No it hasn't been released yet; sorry for the false time prediction.

**Comment by brimoor** [comment] 2022-01-16 18:26
`fiftyone==0.14.3` and `fiftyone-brain==0.7.3` were released earlier this week and contain the fix for this.
