### ISSUE TITLE
[BUG] Setuptools incompatible with packaging on fityone, leading to 'strip_trailing_zero' error

### ISSUE THREAD

**Issue by GustavoOS** [voxel51/fiftyone#4702] opened 2024-08-19 18:55 UTC
### Describe the problem

Fiftyone has the requirements/common.txt in multilple versions with setuptools set with version >= 45.2.0 and  packaging 20.3. However, the expected behaviour changed on setuptools 71 when combined with packaging < 22.0, leading to the exception 'strip_trailing_zero' which occurs on source install. (See https://github.com/pypa/setuptools/issues/4483 for more details)

### Code to reproduce issue

1. Clone 51 repo
2. Create a new virtual environment
3. source install.bash

'strip_trailing_zero' error will occur

### System information

-   **OS Platform and Distribution**: Mac os sonoma M2 14.6.1
-   **Python version** (`python --version`): 3.9
-   **FiftyOne version** (`fiftyone --version`): 0.24.1
-   **FiftyOne installed from** (pip or source): source

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by benjaminpkane** [comment] 2024-08-19 19:03
Hi @GustavoOS. This is an indirect issue. `pip install setuptools<71 fiftyone` should be sufficient. Related to https://github.com/voxel51/fiftyone/pull/4581

**Comment by GustavoOS** [comment] 2024-08-19 20:30
unfortunately this is a bug that affects multiple versions (tried 0.24.1 and 0.23.1, they all have the same error)

**Comment by GustavoOS** [comment] 2024-08-20 12:19
Also, the install.bash script  overrides `pip install setuptools<71 fiftyone`

**Comment by benjaminpkane** [comment] 2024-08-20 13:22
The issue is fixed on `release/v0.25.0` and `develop` branches. You can also edit the `requirement/common.txt` file directly as shown in https://github.com/voxel51/fiftyone/pull/4581/files since you are installing from source

**Closed** 2024-08-20 13:23 UTC
Labels: bug
