### ISSUE TITLE
[BUG] Unable to donwload the mnist dataset

### ISSUE THREAD

**Issue by wuhanstudio** [voxel51/fiftyone#1558] opened 2022-01-21 12:13 UTC
### System information

- Windows
- pip
- FiftyOne v0.14.2, Voxel51, Inc.
- Python 3.7.9

### Describe the problem

Unable to download the mnist dataset

### Code to reproduce issue

```
import fiftyone as fo
import fiftyone.zoo as foz

foz.load_zoo_dataset("mnist", split="test")
```

### Other info / logs

```
Downloading split 'test' to 'C:\Users\hw630\fiftyone\mnist\test'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-7ee5d8bb7cd7> in <module>
      1 # Load the data from fiftyone
----> 2 voc_2012_train = foz.load_zoo_dataset("mnist", split="test")
      3 # voc_2012_train = foz.load_zoo_dataset("voc-2012", split="train", label_types=["detections"])

d:\python37\lib\site-packages\fiftyone\zoo\datasets\__init__.py in load_zoo_dataset(name, split, splits, label_field, dataset_name, dataset_dir, download_if_necessary, drop_existing_dataset, overwrite, cleanup, **kwargs)
    201             overwrite=overwrite,
    202             cleanup=cleanup,
--> 203             **download_kwargs,
    204         )
    205         zoo_dataset = info.get_zoo_dataset()

d:\python37\lib\site-packages\fiftyone\zoo\datasets\__init__.py in download_zoo_dataset(name, split, splits, dataset_dir, overwrite, cleanup, **kwargs)
    119         splits=splits,
    120         overwrite=overwrite,
--> 121         cleanup=cleanup,
    122     )
    123 

d:\python37\lib\site-packages\fiftyone\zoo\datasets\__init__.py in download_and_prepare(self, dataset_dir, split, splits, overwrite, cleanup)
   1002                     num_samples,
   1003                     classes,
-> 1004                 ) = self._download_and_prepare(split_dir, scratch_dir, split)
   1005 
   1006                 # Add split to ZooDatasetInfo

d:\python37\lib\site-packages\fiftyone\zoo\datasets\torch.py in _download_and_prepare(self, dataset_dir, scratch_dir, split)
     91             download_fcn,
     92             get_class_labels_fcn,
---> 93             sample_parser,
     94         )
     95 

d:\python37\lib\site-packages\fiftyone\zoo\datasets\torch.py in _download_and_prepare(dataset_dir, scratch_dir, download_fcn, get_class_labels_fcn, sample_parser)
    534         )
    535     else:
--> 536         raise ValueError("Unsupported label class %s" % label_cls)
    537 
    538     # Write the formatted dataset to `dataset_dir`

TypeError: not all arguments converted during string formatting

```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment] 2022-01-31 16:39
This is a duplicate of https://github.com/voxel51/fiftyone/issues/1451 and should be fixed as of `fiftyone==0.14.3`.

Upgrading should resolve this:

```
pip install --upgrade fiftyone
```

**Closed by brimoor** 2022-01-31 16:39 UTC
Labels: bug
