### ISSUE TITLE
[BUG] `draw_labels` method cannot parse unicode characters

### ISSUE THREAD

**Issue by rusmux** [voxel51/fiftyone#3830] opened 2023-11-21 18:48 UTC
### Describe the problem

When using the `draw_labels` method to draw dataset labels, unicode symbols are parsed as `?`.

### Code to reproduce issue

```Python
import cv2
import fiftyone as fo
import numpy as np

cv2.imwrite("sample.png", np.full((1024, 1024, 3), 255))

sample = fo.Sample(
    filepath="sample.png",
    detections=fo.Detections(detections=[fo.Detection(label="Объект", bounding_box=[0.4, 0.4, 0.2, 0.2])]),
)

dataset = fo.Dataset()
dataset.add_sample(sample)
dataset.draw_labels("sample")
```

![sample](https://github.com/voxel51/fiftyone/assets/85135806/bc0d28aa-2ded-49c7-a97b-f0b1b990dfea)

### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 22.04): macOS Sonoma
-   **Python version** (`python --version`): 3.10.12
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.22.3, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

**Comment by brimoor** [comment] 2024-01-04 16:11
Hi @rusmux 👋 

The issue is that the [default font](https://github.com/voxel51/eta/blob/47ee6b7d69c0431a68e71e6c7b7b4760cc25ed2d/eta/core/annotations.py#L496) used is [lato-regular](https://github.com/voxel51/eta/blob/47ee6b7d69c0431a68e71e6c7b7b4760cc25ed2d/eta/constants.py#L57).

You can manually specify a different font like this (works for me):

```py
import cv2
import fiftyone as fo
import numpy as np

cv2.imwrite("/tmp/sample.png", np.full((1024, 1024, 3), 255))

sample = fo.Sample(
    filepath="/tmp/sample.png",
    detections=fo.Detections(detections=[fo.Detection(label="Объект", bounding_box=[0.4, 0.4, 0.2, 0.2])]),
)

dataset = fo.Dataset()
dataset.add_sample(sample)

dataset.draw_labels("/tmp/sample", font_path="Arial.ttf")
```

**Comment by brimoor** [comment] 2024-01-04 16:21
update: once https://github.com/voxel51/eta/pull/608 is merged then you can just:

```shell
pip install --upgrade voxel51-eta
```

and then this will directly work without manually specifying a new font:

```py
dataset.draw_labels("/tmp/sample")
```

**Closed** 2024-01-04 19:51 UTC
Labels: bug
