### ISSUE TITLE
How to load mp3?

### ISSUE THREAD

**Issue by lminer** [voxel51/fiftyone#1191] opened 2021-08-12 19:37 UTC
I'm trying to find a way to load an mp3. On another issue I was told that this would be possible if we treated an mp3 like a video. I'm not finding a way though to specify the media type. What I would like to do is something like the following:

```
import fiftyone as fo

samples = []
sample = fo.Sample(filepath="moo.mp3")
sample["ground_truth"] = fo.Classification(label="cow mooing")
samples.append(sample)
dataset = fo.Dataset("test_ds")
dataset.add_samples(samples)
```

However, if I try that the app assumes the file is an image. How is the media type determined exactly? There doesn't appear to be a way to pass that information into the constructor.

**Comment by lminer** [comment] 2021-08-12 20:11
Looking through the code, it appears as if the problem is that `mp3` is missing from this list: https://github.com/voxel51/eta/blob/develop/eta/core/video.py#L85, which in turn causes this check to fail: https://github.com/voxel51/fiftyone/blob/c0e31f141c49faa11b832523bb2ccd989ae11e1e/fiftyone/core/media.py#L33

**Comment by brimoor** [comment] 2021-08-12 20:12
Sorry for the confusion in https://github.com/voxel51/fiftyone/issues/1190. FiftyOne datasets can currently only contain image or video files. The `media_type` is inferred [here](https://github.com/voxel51/fiftyone/blob/080471c98bb19fbf68436e89ca82a61324773d73/fiftyone/core/media.py#L23-L37), which explains what you were seeing. I thought you were working with video files that had audio.

Supported for audio-**only** datasets whose `filepath` is an audio format can be added, but some aspects of the App would need some design work. Like what would be shown in the grid view, etc.

But since video datasets with audio are supported, the workaround I would recommend is to store your audio in an audio channel of a video container format like `mp4`.

**Comment by brimoor** [comment] 2021-08-13 01:34
Closing as duplicate of https://github.com/voxel51/fiftyone/issues/1190.

**Closed by brimoor** 2021-08-13 01:34 UTC
Labels: bug
