### ISSUE TITLE
There's an error while trying to export dataset to cvat

### ISSUE THREAD

**Issue by akshayv177** [voxel51/fiftyone#1683] opened 2022-04-14 11:09 UTC
![Screenshot (89)](https://user-images.githubusercontent.com/77143689/163379282-e66023a6-2fae-4ae7-be78-7ffbefd7d686.png)

**Comment by ehofesmann** [comment] 2022-04-14 12:52
This is a duplicate of #1668 which is resolved by #1674

The fix is available through a source build and will be in the next release. For now, the workaround is adding the `Referer` header:
```python
results = dataset.annotate(
    anno_key,
    label_field=label_field,
    headers={"Referer": "https://cvat.org/api/auth/login"},
)
```

**Closed by ehofesmann** 2022-04-14 12:52 UTC
